### ISSUE TITLE
postgresql-42.2.5.jre6.jar vulnerabilities 

### ISSUE THREAD

**Issue by dvasilen** [OHDSI/DatabaseConnectorJars#9]
The postgresql-42.2.5.jre6.jar  driver 

https://github.com/OHDSI/DatabaseConnectorJars/blob/master/inst/java/postgresql-42.2.5.jre6.jar

has been flagged as vulnerable `CVE-2020-13692` https://nvd.nist.gov/vuln/detail/CVE-2020-13692

Would it be possible to update to 42.2.13 or the latest?

**Comment by schuemie** [comment]
Thanks! The DatabaseConnectorJars package has become obsolete with the latest version of DatabaseConnector. This [new version ](http://ohdsi.github.io/DatabaseConnector/news/index.html#databaseconnector-4-0-0-unreleased) requires users to download the jar files manually (CRAN wouldn't allow them anymore due to file size). The version of the Postgres jar it downloads is a lot newer.
